<template>
  <div class="dashboard">
    <div class="page-header"><div><span class="eyebrow">OPERATIONS / OVERVIEW</span><h1>Monitoring dashboard</h1><p>Live signals from the storefront demo and its monitoring SDK.</p></div><button :disabled="loading" @click="loadSummary">{{ loading ? 'Refreshing...' : 'Refresh data' }}</button></div>
    <p v-if="errorMessage" class="error">{{ errorMessage }}</p>
    <section class="metric-grid"><article v-for="metric in metrics" :key="metric.label" class="metric"><span>{{ metric.label }}</span><strong>{{ metric.value }}</strong><small>{{ metric.note }}</small></article></section>
    <div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">EVENT VOLUME</span><h2>Top event names</h2></div><span>Last 200 events</span></div><div v-if="summary.byName.length" class="bars"><div v-for="item in summary.byName" :key="item.name" class="bar-row"><span>{{ item.name }}</span><div><i :style="{ width: `${Math.max(8, (item.count / maxCount) * 100)}%` }"></i></div><strong>{{ item.count }}</strong></div></div><p v-else class="empty">No events received yet. Interact with the storefront to populate this view.</p></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">RECENT ACTIVITY</span><h2>Latest signals</h2></div><RouterLink to="/events">View all</RouterLink></div><div v-if="summary.recent.length" class="activity"><div v-for="event in summary.recent" :key="event.id" class="activity-row"><span class="signal-dot" :class="event.type"></span><div><strong>{{ event.name }}</strong><small>{{ event.payload ? JSON.stringify(event.payload).slice(0, 70) : '' }}</small></div><time>{{ new Date(event.timestamp).toLocaleTimeString() }}</time></div></div><p v-else class="empty">Waiting for the first event.</p></section></div>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { fetchEventSummary, type EventSummaryResponse } from '../api/events'
const loading = ref(false); const errorMessage = ref(''); const summary = ref<EventSummaryResponse>({ total: 0, today: 0, errors: 0, byName: [], recent: [] })
const maxCount = computed(() => Math.max(1, ...summary.value.byName.map((item) => item.count)))
const metrics = computed(() => [{ label: 'Events received', value: summary.value.total, note: 'Current buffer' }, { label: 'Events today', value: summary.value.today, note: 'Demo session' }, { label: 'Error signals', value: summary.value.errors, note: summary.value.errors ? 'Needs attention' : 'No errors detected' }, { label: 'Tracked event types', value: summary.value.byName.length, note: 'Unique names' }])
const loadSummary = async () => { loading.value = true; errorMessage.value = ''; try { summary.value = await fetchEventSummary() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Unable to load dashboard data' } finally { loading.value = false } }
onMounted(() => { void loadSummary() })
</script>
<style scoped>
.dashboard { display: grid; gap: 24px; }.page-header { display: flex; justify-content: space-between; align-items: end; gap: 20px; }.eyebrow { color: var(--accent); font-size: 11px; font-weight: 800; letter-spacing: .14em; }.page-header h1 { margin: 8px 0 4px; font-size: 36px; }.page-header p { margin: 0; color: var(--muted); }.error { color: #b42318; }.metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; }.metric, .panel { background: var(--panel); border: 1px solid var(--line); border-radius: 7px; }.metric { display: grid; gap: 8px; padding: 20px; }.metric span, .metric small, .panel-heading > span, .activity-row small { color: var(--muted); }.metric strong { font-size: 32px; }.metric small { font-size: 12px; }.dashboard-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }.panel { padding: 22px; }.panel-heading { display: flex; justify-content: space-between; gap: 12px; align-items: start; margin-bottom: 22px; }.panel-heading h2 { margin: 6px 0 0; font-size: 20px; }.panel-heading a { color: var(--accent); font-size: 13px; }.bars, .activity { display: grid; gap: 16px; }.bar-row { display: grid; grid-template-columns: 150px 1fr 28px; gap: 12px; align-items: center; font-size: 13px; }.bar-row > div { height: 8px; background: #edf1f4; border-radius: 4px; overflow: hidden; }.bar-row i { display: block; height: 100%; background: var(--accent); border-radius: 4px; }.activity-row { display: grid; grid-template-columns: 10px 1fr auto; gap: 10px; align-items: start; }.signal-dot { width: 8px; height: 8px; margin-top: 5px; border-radius: 50%; background: #3ba77c; }.signal-dot.error { background: #d64545; }.activity-row div { display: grid; gap: 4px; }.activity-row strong { font-size: 13px; }.activity-row small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 11px; }.activity-row time { color: var(--muted); font-size: 11px; }.empty { color: var(--muted); font-size: 14px; line-height: 1.5; }
@media (max-width: 800px) { .metric-grid, .dashboard-grid { grid-template-columns: repeat(2, 1fr); } .page-header { align-items: start; flex-direction: column; } }.bar-row { grid-template-columns: minmax(100px, 150px) 1fr 28px; }
@media (max-width: 520px) { .metric-grid, .dashboard-grid { grid-template-columns: 1fr; } }
</style>
